# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PPPy\fir\DB_PyQT\lesson_5_logging\hw_5_erlGUI\chat_main_wind.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.recepientLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recepientLabel.sizePolicy().hasHeightForWidth())
        self.recepientLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.recepientLabel.setFont(font)
        self.recepientLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.recepientLabel.setObjectName("recepientLabel")
        self.verticalLayout.addWidget(self.recepientLabel)
        self.chatHistoryLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatHistoryLabel.sizePolicy().hasHeightForWidth())
        self.chatHistoryLabel.setSizePolicy(sizePolicy)
        self.chatHistoryLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.chatHistoryLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.chatHistoryLabel.setObjectName("chatHistoryLabel")
        self.verticalLayout.addWidget(self.chatHistoryLabel)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.contactListWigetLabel = QtWidgets.QLabel(self.centralwidget)
        self.contactListWigetLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.contactListWigetLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.contactListWigetLabel.setText("")
        self.contactListWigetLabel.setObjectName("contactListWigetLabel")
        self.gridLayout.addWidget(self.contactListWigetLabel, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout_2.addWidget(self.sendButton, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GB chat client"))
        self.recepientLabel.setText(_translate("MainWindow", "Recepient"))
        self.chatHistoryLabel.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.sendButton.setText(_translate("MainWindow", "SEND"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
